# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

env_variables:
  SPRING_PROFILES_ACTIVE: __SPRING_PROFILES_ACTIVE__
  SPRING_DATASOURCE_URL: __SPRING_DATASOURCE_URL__
  SPRING_DATASOURCE_USERNAME: __SPRING_DATASOURCE_USERNAME__
  SPRING_DATASOURCE_PASSWORD: __SPRING_DATASOURCE_PASSWORD__
  GOOGLE_CALENDAR_CREDENTIALS: __GOOGLE_CALENDAR_CREDENTIALS__
  REDIRECT_URI: __REDIRECT_URI__