# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
instance_class: F2 
env: flex

runtime_config:
  operating_system: "ubuntu22" 
  runtime_version: "17"

network:
  session_affinity: true

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cpu_utilization:
    target_utilization: 0.7

readiness_check:
  check_interval_sec: '30'
  timeout_sec: '4'
  failure_threshold: 2
  success_threshold: 1
  app_start_timeout_sec: '60'

