# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

env_variables:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: sm://projects/293911148663/secrets/SPRING_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: sm://projects/293911148663/secrets/SPRING_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: sm://projects/293911148663/secrets/SPRING_DATASOURCE_PASSWORD